### PR TITLE
Add cf-buildpacks-eng bot to list of bots to allow automerged commits from

### PR DESCRIPTION
**Pull request by sophiewigmore**
## Summary

Add @cf-buildpacks-eng bot to list of bots to allow automerged commits from. 

## Use Cases

@cf-buildpacks-eng bot makes commits such as the ones on this PR : https://github.com/paketo-buildpacks/bundler/pull/136/commits/3f5c1f51fdf278ff96c8d7f99f0c714bfae86855, which used to automerge. Since we have updated our actions to only allow automerging of bot commits, these PRs no longer automerge. I believe that these should still automerge.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

### CODE REVIEW

**Comment by fg-j** [comment]
@sophiewigmore That bot's commits also won't automerge unless they are signed. Does that bot have a GPG key set up?

**Comment by ryanmoran** [comment]
Can we not include this bot in the defaults list and instead override it in the workflow? I believe that is possible.

**Comment by sophiewigmore** [comment]
@ryanmoran could you elaborate on what you mean by overriding it in the workflow?

**Comment by fg-j** [comment]
The action accepts an [optional input `bots`](https://github.com/paketo-buildpacks/github-config/blob/c5f8396aab9a6d518e872ee2760b543d98427d49/actions/pull-request/check-human-commits/action.yml#L16) that can be used to set whatever acceptable bots you want. These just default to the three most common committers on our PRs. The set you pass to `bots` will be considered the non-human committers and will get past the check.

**Comment by sophiewigmore** [comment]
Closed in favour of looking into having `paketo-bot` perform the types of commits mentioned in this PR instead.

**Pull request closed without merging**
