### PR TITLE
Retry stack USN polling on 504 error

### PR DESCRIPTION
**Pull request by sophiewigmore**
## Summary

Since setting up release failure notification issues on the new Jammy Tiny stack, we have already seen many instances of failed builds that occur because of intermittent 504 errors when polling for USNs. ([example](https://github.com/paketo-buildpacks/jammy-tiny-stack/issues/20))
 All of these notifications are red herrings, because the issue usually disappears when the job runs again. It's creating a lot of notifications.

This PR just allows for a retry in instances where polling fails do to a 504 error, so we can hopefully get less failures during this step.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
I’m curious if you considered using an [exponential backoff](https://en.m.wikipedia.org/wiki/Exponential_backoff) rather than a fixed retry interval (e.g. this [golang implementation](https://github.com/cenkalti/backoff)). Might protect us from being rate limited on our retries.

**Comment by sophiewigmore** [comment]
@fg-j I hadn't tried this, interesting idea!  My first thought is that doing an exponential backoff in this scenario feels overkill on the level of the action itself running, because all I want to do is try one more time if a query fails the first time--which seemed to have fully correctional results when used on my local workstation. If anything, it might make more sense if we used that algorithm to figure out how often to run the `create-release` workflow itself, which feels like a bigger change

**Comment by sophiewigmore** [comment]
@fg-j check out the newest commit -is this what you had in mind? I also expanded it to do retries on non-504 errors as well.

**Review by fg-j — APPROVED** [review]
I just played around with this and managed to get some 504s to test out the backoff. It seems effective! LGTM

**Pull request merged**
