### PR TITLE
Update-dependencies workflow output PRs now include versions

### LINKED ISSUE #329: Make dependency update PR names more informative
Automated PRs generated by concourse pipelines to update dependencies have names like: "Updating version for dotnet-runtime for 3.1.X". This is handy because it's easy to determine, at a glance, what the PR is changing. (Like if you're looking at the changelog on a draft release to determine the correct semver version for the next one).

PRs opened by the update dependencies workflow are [all named the same thing](https://github.com/paketo-buildpacks/github-config/blob/7f0e3f54cb4a363378e50de74cb7b1cf70e6bcc4/implementation/.github/workflows/update-dependencies.yml#L29)

It would be helpful if these PRs could somehow give a hint about the changes they made.

### PR DESCRIPTION
**Pull request by sophiewigmore**
## Summary

Resolves #329.

Tested in https://github.com/paketo-buildpacks/node-engine/pull/355, you can see the Pull Request title includes a comma-separated list of new versions.

The PR title will now be: `"Updates buildpack.toml with new dependency versions: X.X.X, X.X.X"`

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by sophiewigmore** [comment]
TODO: make PR message contain versions, not commit.

**Comment by fg-j** [comment]
I tried running the commands added to the workflow on my machine with jam v1.0.1 and the node-engine buildpack. It didn't work quite how I expected:

```bash
git co v0.5.0
Note: switching to 'v0.5.0'.

versions="$(jam update-dependencies \
--buildpack-file "${PWD}/buildpack.toml")"

echo $versions
Updating buildpack.toml with new versions:
[12.22.4 12.22.5 14.17.4 14.17.5 16.6.2 16.7.0]

versions="$(echo ${versions} | cut -d'[' -f2- | cut -d']' -f-1 | sed 's/ /, /g')"

echo "::set-output name=new_versions::${versions}"
::set-output name=new_versions::Updating, buildpack.toml, with, new, versions:,
12.22.4, 12.22.5, 14.17.4, 14.17.5, 16.6.2, 16.7.0
```

**Comment by sophiewigmore** [comment]
@fg-j the latest changes to `jam` included in https://github.com/paketo-buildpacks/github-config/pull/339/commits/9ba5d9ea7dd33765fdcc0f521ae9b2240263e2c5 should now put everything on one line.

**Review by fg-j — APPROVED** [review]
Looks great!

**Pull request merged**
