### PR TITLE
Add exponential backoff failure handling to release asset downloading.

### PR DESCRIPTION
**Pull request by robdimsdale**
## Summary

This PR adds retry logic with exponential backoff to the download-asset action. To achieve this, this PR rewrites the action in Go.

A side benefit of writing this in Go is that it makes testing feasible, so this PR adds tests for the action.

## Use Cases

Roughly half of the monthly CI failures across the various stacks pipelines are issues downloading release assets that would likely be succesful upon retry.

Therefore adding retry logic should significantly reduce the number of flakes in the stacks pipelines.

It will also reduce the number of flakes in other pipelines that leverage this action, too, though we haven't performed any failure analysis on other pipelines.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
Does the action need an `action.yml`? It seems like other golang + Dockerfile actions do (e.g. the create release action)

**Comment by fg-j** [comment]
@robdimsdale I notice that you don't test that the exponential backoff actually occurs, and that you also don't test when writing the output artifact fails. Are these omissions intentional?

**Comment by robdimsdale** [comment]
@fg-j yeah, i thought about both of those things.

### Exponential backoff testing
The exponential backoff happens during the error cases, but it's not tested for explicitly. We could assert this happens by validating that output contains "retrying" for an error case.

I'm happy to add this, I was somewhat on the fence about it.

### Handling errors when writing to the (created) file

I couldn't find a good way to test this with the test infrastructure we have (i.e. the integration test). If you have a good way to force a failure to write to a file after it was successfully created, please show me!

**Comment by fg-j** [comment]
I'm ok with not testing these things! The code is quite simple and I see that you've got proper error handling around the failure-to-write case. Just wanted to make sure the omissions were intentional.

**Review by fg-j — APPROVED** [review]

**Pull request merged**
