### PR TITLE
Adds unit test script and workflow for running tests

### PR DESCRIPTION
**Pull request by thitch97**

### CODE REVIEW

**Comment by ryanmoran** [comment]
@ForestEckhardt that unit test was already fixed here: https://github.com/paketo-buildpacks/github-config/pull/16

**Comment by ForestEckhardt** [comment]
@ryanmoran Do you want me to go in and revert?

**Comment by arjun024** [comment]
@thitch97 @ryanmoran Any idea why the tests are not running against the updated base branch? Do you have an option to 'update base branch' that I do not have have?

**Comment by ryanmoran** [comment]
@arjun024 I think the history of the branch was messed up. I've rebased off master and force-pushed to give it just the one commit. Tests are passing.

**Pull request merged**
