### PR TITLE
Refactors clone-all-repos script

### PR DESCRIPTION
**Pull request by ryanmoran**
## Summary

Refactors the `scripts/clone-all-repos.sh` script so that it passes `shellcheck`, includes some more informative log output, and flows in a bit simpler structure.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@ryanmoran this script doesn't run for me now, I get the following error:
```
  Fetching teams belonging to the paketo-buildpacks GitHub organization...
jq: error (at <stdin>:4): Cannot index string with string "slug"
```

**Comment by ryanmoran** [comment]
I didn't change the API that is called. If you are seeing a permissions error, then its either that your token is not the one you previously used, or GitHub has changed their API permissions since you last ran this.

**Comment by ForestEckhardt** [comment]
@sophiewigmore There was a change to the script where you now need to set the Github token before running the command.

**Comment by ryanmoran** [comment]
> @sophiewigmore There was a change to the script where you now need to set the Github token before running the command. Here is the PR that made the change #276.

I changed the interface for this. You now need to provide the token via a `--token` flag that is required. The script will fail indicating that the flag is required if it is missing. The error @sophiewigmore seems to indicate that she provided a token, but that the permissions are not sufficient to query that API.

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
